name: Upload Python Package

on:
  release:
    types: [created,prereleased]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
    - name: Build
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: Upload documentation
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        pip install -e .
        doc/build_doc.sh
